// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package books

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID        int32
	Title     string
	Author    string
	Isbn      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
